# Generated by Django 5.2.5 on 2025-09-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='price',
            new_name='preco',
        ),
    ]
